### ISSUE TITLE
Application error hosting in heroku

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [2Epik4u/Wrapper-Online#5]
Since I host wrapper in heroku it just say application error.

**Comment by BonziPOPEGuy** [comment]
switch master to add-license-1

**Comment by ZyrusplaysAnimations** [comment]
There's no add-licence

**Comment by BonziPOPEGuy** [comment]
then idk, fix it yourself.

**Comment by christopher3242** [comment]
There no flash played 
![image](https://user-images.githubusercontent.com/52284167/96099445-8b20c100-0ed3-11eb-9ec8-198f00132173.png)

**Comment by 2Epik4u** [comment]
You are running a older version of wrapper online. Use the newer version (or just replace the config.json on the GitHub repo)

**Comment by HelperPlugin2** [comment]
Uh oh

**Comment by HargoTheVyonder** [comment]
..

**Comment by DanieliusWrapper** [comment]
Ok is rehosting
